### ISSUE TITLE
GJFY - only INDEX Page

### ISSUE THREAD

**Issue by gitTBE** [sstark/gjfy#2]
Hello everybody,
I've been trying to get gjfy to work for quite a while.
I tried Docker first, currently I've tried Ubuntu 20.04. The same screen is displayed in both systems:

![gjfy](https://user-images.githubusercontent.com/69964076/90753997-94c5e800-e2d9-11ea-86b9-6b64fefc949a.png)

Can someone help me tell us where I took the wrong turn or what is missing?

Possibly. I just get it wrong at this point, I also tried to download the command line, but unfortunately I can't really keep up with that.

Is anyone able to help me?

**Comment by sstark** [comment]
I don't think you are missing anything. The index page is not very useful, as you noticed. Mainly to download the command line client. Which is in turn just a simple example shell script that shows how to create a secret.
You can use the client to create a new secret, it will return a URL that you can send to somebody to read that secret.
There is really nothing more to see, especially no interactive web page or anything like that. If you want to use something more visual you probably should have a look at similar projects that focus more on the graphical appearance.

**Comment by gitTBE** [comment]
Many thanks for the answer. It sounds like I'm on the right track.

If I download the command line, how do I do it so that a URL is returned to me?

Sry, for my questions, I'm still at the very beginning when it comes to my experience with Ubuntu etc.

**Comment by sstark** [comment]
After setting up and running gjfy and after creating an authentication token, you run the script like described here:

  https://github.com/sstark/gjfy#gjfy-post

What is missing from the documentation is that you have to make the script executable first (`chmod +x gjfy-post`). The code is short, you can see how it works by reading it.

Maybe an installer script that puts everything in the right place would be handy, but it does not exist as of now :)

**Comment by gitTBE** [comment]
so slowly I understand how it works. Actually very simple.

I now get this error:
![gjfy_jq](https://user-images.githubusercontent.com/69964076/91287361-f1208000-e78f-11ea-8d35-03532b9b9e9c.png)
![gjfy_jq_code](https://user-images.githubusercontent.com/69964076/91287900-a0f5ed80-e790-11ea-9b95-d9e2d448cfa8.png)



What did i forget? What does this error mean?

**Comment by sstark** [comment]
You need to install the _jq_ package:  `sudo apt install jq`

**Comment by gitTBE** [comment]
THANK YOU SO MUCH for the help!
It works now. Now the next step for me is to send the whole thing directly via email. Everything works locally so far!

Thanks again!

**Comment by gitTBE** [comment]
Here I am again with a question.
I can send email over SSMTP using the ECHO command.
Unfortunately, it doesn't work at GJFY.
I ran ./gjfy -notify, then stopped the service -> reload -> and tested it again.

With ./gjfy-post gitTBE abc I get the generated links in the console -> no mail.

When I start ./gjfy-post -notify gitTBE abc, I get an unauthorized

Do you have any idea what I missed this time?

**Comment by gitTBE** [comment]
Hello,
I also tested it with Postfix, same problem.
I use Gmail as a relayhost,.

> Here I am again with a question.
> I can send email over SSMTP using the ECHO command.
> Unfortunately, it doesn't work at GJFY.
> I ran ./gjfy -notify, then stopped the service -> reload -> and tested it again.
> With ./gjfy-post gitTBE abc I get the generated links in the console -> no mail.
> When I start ./gjfy-post -notify gitTBE abc, I get an unauthorized
> Do you have any idea what I missed this time?

**Comment by sstark** [comment]
gjfy needs the `mail` command set up and working. In Debian you can use the `bsd-mailx` package for instance.

**Comment by sstark** [comment]
Also you are mixing up `gjfy` (the server) and `gjfy-post` (the client) in your previous post. The latter has nothing to do with email, and it does not understand the `-notify` parameter.

**Comment by gitTBE** [comment]
Many thanks for your help!
